/**
 * Proofline real (Groq-backed) Strands agent — server-side only.
 *
 * Uses the installed Strands `OpenAIModel` against Groq's OpenAI-compatible
 * Chat Completions endpoint (openai/gpt-oss-120b). The Strands Agent remains
 * the orchestration layer; no separate OpenAI/Groq client is created here.
 *
 * SERVER ONLY: reads process.env.GROQ_API_KEY, never prints or exposes it, and
 * must never be imported from client/browser code.
 */

import { Agent, FunctionTool, type AgentResult } from '@strands-agents/sdk';
import { OpenAIModel } from '@strands-agents/sdk/models/openai';
import type { EvidenceLedger } from '../evidence/evidence-ledger';
import type {
  ReadinessFinding,
  ReadinessResult,
} from '../readiness/readiness-result';
import { verifyPdfPageLimitTool } from './proofline-verification-tools';
import { verifyLocalRepositoryTool } from './proofline-repository-tools';

/** Verified Groq model id for the real agent. */
const GROQ_MODEL_ID = 'openai/gpt-oss-120b';

/** Groq OpenAI-compatible endpoint. */
const GROQ_BASE_URL = 'https://api.groq.com/openai/v1';

/** Environment variable that must carry the Groq API key (server-side only). */
const GROQ_API_KEY_ENV_VAR = 'GROQ_API_KEY';

/** Concise, honest system prompt for the real agent. */
const PROOFLINE_REAL_SYSTEM_PROMPT =
  "Proofline verifies research submission packages. " +
  "The agent has deterministic tools for PDF page-limit verification and local " +
  "repository verification. " +
  "Use the verification tools when the user's request requires those checks. " +
  "Do not claim a verification was performed unless a tool actually returned " +
  "the corresponding result/evidence.";

/** Deterministic health check, identical to the mock-agent health_check tool. */
const healthCheckTool = new FunctionTool({
  name: 'health_check',
  description:
    'Deterministic Proofline health check. Proves the custom tool executed. Accepts no input.',
  inputSchema: { type: 'object', properties: {} },
  callback: () => ({
    status: 'ok',
    proof: 'Proofline health_check tool executed successfully',
  }),
});

/**
 * Reads and validates the Groq API key from the server environment.
 * Throws a clear error when the key is missing; never prints or exposes it.
 */
function requireGroqApiKey(): string {
  const apiKey = process.env[GROQ_API_KEY_ENV_VAR];
  if (typeof apiKey !== 'string' || apiKey.trim().length === 0) {
    throw new Error('GROQ_API_KEY is required to run the real Proofline agent.');
  }
  return apiKey;
}

/**
 * Constructs a real Strands Agent backed by Groq (OpenAI-compatible Chat
 * Completions) with the three Proofline tools registered.
 */
export function createProoflineRealAgent(): Agent {

  return new Agent({

    model: new OpenAIModel({

      api: 'chat',

      modelId: GROQ_MODEL_ID,

      apiKey: requireGroqApiKey(),

      clientConfig: { baseURL: GROQ_BASE_URL },

    }),

    tools: [healthCheckTool, verifyPdfPageLimitTool, verifyLocalRepositoryTool],

    systemPrompt: PROOFLINE_REAL_SYSTEM_PROMPT,

    contextManager: false,

    printer: false,

  });

}

/**
 * Runs the real Proofline agent with the supplied prompt and returns a concise,
 * JSON-safe result. Never returns raw SDK objects or the API key.
 */
export async function runProoflineRealAgent(
  prompt: string,
): Promise<{ text: string; stopReason: string }> {
  const agent = createProoflineRealAgent();
  const result: AgentResult = await agent.invoke(prompt);
  return {
    text: result.toString(),
    stopReason: result.stopReason,
  };
}

/**
 * Authoritative deterministic facts handed to the explanation agent.
 * Built by the caller from the already-computed runPreflight() result —
 * never generated by the model.
 */
export interface PreflightFacts {
  /** Overall readiness status, e.g. 'ready' | 'blocked' | 'human_review'. */
  readinessStatus: string;
  /** Deterministic readiness counts from the ReadinessResult. */
  passedCount: number;
  blockingCount: number;
  humanReviewCount: number;
  /** Findings projected deterministically from the evidence ledger. */
  findings: readonly ReadinessFinding[];
  /** The immutable evidence ledger for this run. */
  evidenceLedger: EvidenceLedger;
  /** Whether the manuscript PDF was provided and verified. */
  pdfVerified: boolean;
  /** Whether the local repository was provided and verified. */
  repositoryVerified: boolean;
}

/** System prompt for the facts-only explanation agent (no verification tools). */
const PROOFLINE_FACTS_SYSTEM_PROMPT =
  'Proofline explains already-computed deterministic submission verification. ' +
  'The caller supplies authoritative verification facts (readiness status, ' +
  'counts, findings, evidence ledger entries, verification flags). ' +
  'Treat those supplied facts as authoritative and final. ' +
  'Do NOT perform verification yourself: do not call any verification tool, ' +
  'do not inspect files, and do not fetch URLs. ' +
  'Do NOT invent or alter verification results: never change the readiness ' +
  'status, counts, finding statuses, page counts, evidence IDs, timestamps, ' +
  'repository facts, or rule identities, and never claim a check exists that ' +
  'is not in the supplied facts. ' +
  'Explain what was verified, explain why the submission has the supplied ' +
  'readiness state, identify the most important issues requiring human ' +
  'action, and recommend concrete remediation steps based ONLY on the ' +
  'supplied findings and evidence. ' +
  'Clearly distinguish VERIFIED FACTS (from the supplied results) from ' +
  'RECOMMENDATIONS (your advice).';

/** Headings the explanation must include so the UI can display it. */
const PROOFLINE_EXPLANATION_SECTIONS =
  'Use exactly these markdown sections in this order:\n' +
  '## Summary\n' +
  '## Verified state\n' +
  '## Issues\n' +
  '## Recommended actions';

/**
 * Renders authoritative deterministic facts as the agent's user prompt.
 * Only facts/results are included — never PDF bytes, file paths on the
 * server, or secrets. JSON-serializes the supplied structures verbatim so the
 * model cannot mistake its own words for evidence.
 */
export function buildPreflightFactsPrompt(facts: PreflightFacts): string {
  const payload = {
    readinessStatus: facts.readinessStatus,
    counts: {
      passedCount: facts.passedCount,
      blockingCount: facts.blockingCount,
      humanReviewCount: facts.humanReviewCount,
    },
    findings: facts.findings,
    evidenceLedger: facts.evidenceLedger,
    pdfVerified: facts.pdfVerified,
    repositoryVerified: facts.repositoryVerified,
  };
  return (
    'Authoritative deterministic Proofline verification facts ' +
    '(do not alter or invent):\n' +
    JSON.stringify(payload, null, 2) +
    '\n\n' +
    PROOFLINE_EXPLANATION_SECTIONS
  );
}

/**
 * Constructs the facts-only explanation agent: same Groq model/provider, but
 * with NO verification tools registered, so it cannot re-verify or invent
 * tool results. It can only explain the supplied facts.
 */
export function createProoflineFactsAgent(): Agent {
  return new Agent({
    model: new OpenAIModel({
      api: 'chat',
      modelId: GROQ_MODEL_ID,
      apiKey: requireGroqApiKey(),
      clientConfig: { baseURL: GROQ_BASE_URL },
    }),
    tools: [],
    systemPrompt: PROOFLINE_FACTS_SYSTEM_PROMPT,
    contextManager: false,
    printer: false,
  });
}

/**
 * Explains an already-computed deterministic preflight result.
 * Backward compatible: runProoflineRealAgent(prompt) is unchanged.
 */
export async function runProoflineAgentWithFacts(
  facts: PreflightFacts,
): Promise<{ text: string; stopReason: string }> {
  const agent = createProoflineFactsAgent();
  const result: AgentResult = await agent.invoke(buildPreflightFactsPrompt(facts));
  return {
    text: result.toString(),
    stopReason: result.stopReason,
  };
}

/**
 * Builds PreflightFacts from an already-computed deterministic preflight
 * result. Pure projection — no validation logic, no model calls.
 */
export function preflightFactsFromResult(result: {
  readiness: ReadinessResult;
  findings: readonly ReadinessFinding[];
  evidenceLedger: EvidenceLedger;
  pdfVerified: boolean;
  repositoryVerified: boolean;
}): PreflightFacts {
  return {
    readinessStatus: result.readiness.status,
    passedCount: result.readiness.passedCount,
    blockingCount: result.readiness.blockingCount,
    humanReviewCount: result.readiness.humanReviewCount,
    findings: result.findings,
    evidenceLedger: result.evidenceLedger,
    pdfVerified: result.pdfVerified,
    repositoryVerified: result.repositoryVerified,
  };
}